In [7]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv("CBOTYM.csv")

In [12]:
TODAYVOLATILITY = np.std(df['close'].values,ddof =30)#当日市场波动

In [17]:
YESTERDAYVOLATILITY = np.std(df['close'].values[1:],ddof =30)#昨日市场波动

In [18]:
LOOKBACKDAYS=0

In [19]:
DELTAVOLATILITY=(TODAYVOLATILITY-YESTERDAYVOLATILITY)/TODAYVOLATILITY #市场波动的变动率

In [23]:
#计算自适应参数 

In [24]:
if(abs(df['close'].values[-1]-df['open'].values[-1])<=30):
       LOOKBACKDAYS = 20
else:
       LOOKBACKDAYS = 1+DELTAVOLATILITY
   

In [25]:
LOOKBACKDAYS=round(LOOKBACKDAYS,0)

In [26]:
LOOKBACKDAYS=min(LOOKBACKDAYS,40)

In [27]:
LOOKBACKDAYS=max(LOOKBACKDAYS,20);

In [28]:
import talib as ta

In [63]:
MIDLINE=ta.MA(df['close'].values,timeperiod = LOOKBACKDAYS,matype=0)
BAND=np.std(df['close'].values,ddof =LOOKBACKDAYS) #自适应布林通道中轨
UPBAND=MIDLINE+2*BAND#自适应布林通道上轨
DNBAND=MIDLINE-2*BAND#自适应布林通道下轨
BUYPOINT1=(df['high'].values)#自适应唐奇安通道上轨
BUYPOINT2=(df['high'].values[:-1])
ta.EMA(np.array(BUYPOINT1), timeperiod=60)

array([           nan,            nan,            nan, ...,
       30952.39054522, 30951.45970767, 30950.00201234])

In [61]:
df['high'].values[-LOOKBACKDAYS:]

array([30985., 30999., 30998., 30996., 30995., 30986., 30988., 30998.,
       30985., 30963., 30971., 30959., 30967., 30970., 30984., 30988.,
       30985., 30931., 30924., 30907.])

In [62]:
df['high'].values[-(LOOKBACKDAYS+1):-1].shape[0]

20

In [64]:
VAR1=ta.EMA(ta.EMA(np.array(BUYPOINT1), timeperiod=60), timeperiod=60)[-LOOKBACKDAYS:]
VAR2=ta.EMA(ta.EMA(np.array(BUYPOINT2), timeperiod=60), timeperiod=60)[-(LOOKBACKDAYS+1):-1]


In [65]:
VAR1

array([30994.40776144, 30992.45329308, 30990.63084816, 30988.93172046,
       30987.34870772, 30985.86634756, 30984.48189146, 30983.20126281,
       30982.00516676, 30980.86578729, 30979.78929089, 30978.75987914,
       30977.78422157, 30976.86312486, 30976.00910976, 30975.22306757,
       30974.49823416, 30973.7733919 , 30973.04179569, 30972.28639296])

In [50]:
VAR1=VAR1[~pd.isnull(VAR1)]
VAR2=VAR2[~pd.isnull(VAR2)]

In [77]:
VAR2.max()

30998.727945827406

In [78]:
(VAR1-VAR2).max()/VAR2.max()

-4.676565040932323e-05

In [53]:
max(VAR2)

31103.477709291077

In [52]:
控盘=max(VAR1)-max(VAR2)
控盘

0.0